"""Constants for the Elräkning integration."""

DOMAIN = "elrakning"
NORD_POOL_DOMAIN = "nordpool"
ELECTRICITY_PROVIDER_CONFIG_KEY = "electricity_provider"
ELECTRICITY_PROVIDER_CONFIG_DATA_KEY = "electricity_provider_config"
GREENELY_PROVIDER = "greenely"
EON_GRID_PROVIDER = "eon_grid"
EON_GRID_CONFIG_KEY = "eon_grid_config"
GRID_CONFIG_KEY = "grid_config"
EON_GRID_UPDATE_EVENT = "elrakning_eon_grid_update"
SOLAR_WEATHER_UPDATE_EVENT = "elrakning_solar_weather_update"
SUPPORTED_ELECTRICITY_PROVIDERS = {
    GREENELY_PROVIDER: "Greenely",
}
GREENELY_EMAIL = "email"
GREENELY_PASSWORD = "password"
GREENELY_FACILITY_ID = "facility_id"
ELECTRICITY_PROVIDER_UPDATE_EVENT = "elrakning_electricity_provider_update"
INTEGRATION_READY_EVENT = "elrakning_integration_ready"
APP_SHADOW_ENABLED = "app_shadow_enabled"
APP_SHADOW_URL = "app_shadow_url"
APP_SHADOW_TOKEN = "app_shadow_token"
DIAGNOSTIC_STAGE_OPTION = "diagnostic_stage"
DIAGNOSTIC_STAGE_MAX = 15
CLEAN_INSTALL_RESET_SERVICE = "clean_install_reset"
CLEAN_INSTALL_PENDING_OPTION = "pending_clean_install_reset"
CLEAN_INSTALL_ARCHIVE_REFERENCE_OPTION = "clean_install_archive_reference"
CLEAN_INSTALL_CONFIRM_OPTION = "clean_install_confirm"
CLEAN_INSTALL_RECEIPT_OPTION = "clean_install_reset_receipt"
